spring.application.name=paiement-service
server.port=8084

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/fatourati_BackOffice
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT (même secret que utilisateur-service — token partagé back-office)
jwt.secret=FatouratiBackOfficeSecretKey2025VeryLongSecretForHS256Algorithm!!
jwt.expiration=86400000

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# URLs des services amont (validation inter-services)
creancier.service.url=http://localhost:8081/api
creance.service.url=http://localhost:8082/api
